#for more info https://www.youtube.com/watch?v=wxebTn_a930&feature=youtu.be
server:
  port: 8081

spring:
  datasource:
    jpa:
      show-sql: true

fitnet:
  version: 1.0.0
  check-user-scopes: true
  force-https: false
  datasource:
    url: jdbc:mysql://localhost:3306/tmp?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: puntos
    action: validate