##########################################
###############ESTRUCTURA#################
##########################################

CREATE TABLE OAUTH_CLIENT_DETAILS (
    CLIENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    CLIENT_SECRET VARCHAR(255) NOT NULL,
    RESOURCE_IDS VARCHAR(255) DEFAULT NULL,
    SCOPE VARCHAR(255) DEFAULT NULL,
    AUTHORIZED_GRANT_TYPES VARCHAR(255) DEFAULT NULL,
    WEB_SERVER_REDIRECT_URI VARCHAR(255) DEFAULT NULL,
    AUTHORITIES VARCHAR(255) DEFAULT NULL,
    ACCESS_TOKEN_VALIDITY INT(11) DEFAULT NULL,
    REFRESH_TOKEN_VALIDITY INT(11) DEFAULT NULL,
    ADDITIONAL_INFORMATION VARCHAR(4096) DEFAULT NULL,
    AUTOAPPROVE VARCHAR(255) DEFAULT NULL
);

CREATE TABLE PERMISO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(60) UNIQUE KEY
);

CREATE TABLE ROL (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(60) UNIQUE KEY
);

CREATE TABLE PERMISO_ROL (
    PERMISO_ID INT,
    FOREIGN KEY (PERMISO_ID)
        REFERENCES PERMISO (ID),
    ROL_ID INT,
    FOREIGN KEY (ROL_ID)
        REFERENCES ROL (ID)
);

CREATE TABLE USUARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(24) UNIQUE KEY NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ENABLED BIT(1) NOT NULL,
    ACCOUNT_EXPIRED BIT(1) NOT NULL,
    CREDENTIALS_EXPIRED BIT(1) NOT NULL,
    ACCOUNT_LOCKED BIT(1) NOT NULL
);

CREATE TABLE ROL_USUARIO (
    ROL_ID INT,
    FOREIGN KEY (ROL_ID)
        REFERENCES ROL (ID),
    USUARIO_ID INT,
    FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIO (ID)
);

##########################################
################DATOS#####################
##########################################

#Configuracion servidor de recursos
INSERT INTO OAUTH_CLIENT_DETAILS (
  CLIENT_ID,CLIENT_SECRET,
  RESOURCE_IDS,
  SCOPE,
  AUTHORIZED_GRANT_TYPES,
  WEB_SERVER_REDIRECT_URI,AUTHORITIES,
  ACCESS_TOKEN_VALIDITY,REFRESH_TOKEN_VALIDITY,
  ADDITIONAL_INFORMATION,AUTOAPPROVE)
VALUES(
  'USER_CLIENT_APP','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
                    'USER_CLIENT_RESOURCE,USER_ADMIN_RESOURCE',
                    'role_admin,role_user',
                    'authorization_code,password,refresh_token,implicit',
                    NULL,NULL,
                    900,3600,
                    '{}',NULL);

INSERT INTO PERMISO (NAME) VALUES
  ('can_create_user'),
  ('can_update_user'),
  ('can_read_user'),
  ('can_delete_user');

INSERT INTO ROL (NAME) VALUES
  ('role_admin'),('role_user');

INSERT INTO PERMISO_ROL (PERMISO_ID, ROL_ID) VALUES
  (1,1),
  (2,1),
  (3,1),
  (4,1),
  (3,2);

INSERT INTO USUARIO (
  USERNAME,PASSWORD,
  EMAIL,ENABLED,ACCOUNT_EXPIRED,CREDENTIALS_EXPIRED,ACCOUNT_LOCKED) VALUES (
  'admin','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
  'william@gmail.com',1,0,0,0),
  ('user','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
   'john@gmail.com',1,0,0,0);

INSERT INTO ROL_USUARIO (ROL_ID, USUARIO_ID)
VALUES
  (1, 1),
  (2, 2) ;
